INSERT INTO category (name) VALUES 
("beauty"),
("mascara"),
("eyeshadow"),
("face powder"),
("lipstick"),
("nail polish"),
("fragrances"),
("perfumes"),
("furniture"),
("beds"),
("sofas"),
("bedside tables"),
("office chairs"),
("bathroom"),
("fruits"),
("groceries"),
("meat"),
("pet supplies"),
("cat food"),
("cooking essentials"),
("vegetables"),
("dog food"),
("dairy"),
("seafood"),
("condiments"),
("desserts"),
("beverages"),
("coffee"),
("health supplements"),
("grains"),
("household essentials"),
("home decor"),
("swing"),
("home-decoration"),
("photo frame"),
("artificial plants"),
("plant accessories"),
("lighting"),
("kitchen tools"),
("utensils"),
("kitchen-accessories"),
("drinkware"),
("cups"),
("kitchen appliances"),
("blenders"),
("cookware"),
("woks"),
("cutting boards"),
("juicers"),
("slicers"),
("cooktops"),
("strainers"),
("glasses"),
("graters"),
("ice cube trays"),
("cutlery"),
("storage"),
("microwaves"),
("organization"),
("pans"),
("dinnerware"),
("plates"),
("tongs"),
("pots"),
("turners"),
("serveware"),
("trays"),
("baking"),
("peelers"),
("laptops"),
("apple"),
("clothing"),
("men's shirts"),
("mens-shirts"),
("men's t-shirts"),
("footwear"),
("athletic shoes"),
("mens-shoes"),
("sports cleats"),
("casual shoes"),
("watches"),
("leather watches"),
("mens-watches"),
("luxury watches"),
("electronics"),
("smart speakers"),
("mobile-accessories"),
("wireless earphones"),
("over-ear headphones"),
("wireless chargers"),
("chargers"),
("power banks"),
("smartwatches"),
("phone accessories"),
("camera accessories"),
("selfie accessories"),
("motorcycles"),
("motorcycle"),
("sportbikes"),
("scooters"),
("personal care"),
("hand soap"),
("skin-care"),
("body wash"),
("body lotion"),
("smartphones"),
("oppo"),
("realme"),
("samsung galaxy"),
("vivo"),
("sports equipment"),
("american football"),
("sports-accessories"),
("baseball"),
("basketball"),
("cricket"),
("badminton"),
("football"),
("golf"),
("tennis"),
("volleyball"),
("eyewear"),
("sunglasses"),
("party glasses"),
("tablets"),
("dresses"),
("tops"),
("girls' dresses"),
("sedans"),
("vehicles"),
("vehicle"),
("sports cars"),
("hatchbacks"),
("compact cars"),
("suvs"),
("minivans"),
("fashion accessories"),
("handbags"),
("womens-bags"),
("leather bags"),
("designer bags"),
("backpacks"),
("gowns"),
("womens-dresses"),
("corsets"),
("skirts"),
("suits"),
("earrings"),
("womens-jewellery"),
("slippers"),
("womens-shoes"),
("heel shoes"),
("women's shoes"),
("womens-watches"),
("women's watches"),
