/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WishlistImport } from './routes/wishlist'
import { Route as CustomerImport } from './routes/customer'
import { Route as CartImport } from './routes/cart'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ShopIndexImport } from './routes/shop.index'
import { Route as ShopCategoryImport } from './routes/shop.$category'
import { Route as ProductIdImport } from './routes/product.$id'

// Create/Update Routes

const WishlistRoute = WishlistImport.update({
  path: '/wishlist',
  getParentRoute: () => rootRoute,
} as any)

const CustomerRoute = CustomerImport.update({
  path: '/customer',
  getParentRoute: () => rootRoute,
} as any)

const CartRoute = CartImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ShopIndexRoute = ShopIndexImport.update({
  path: '/shop/',
  getParentRoute: () => rootRoute,
} as any)

const ShopCategoryRoute = ShopCategoryImport.update({
  path: '/shop/$category',
  getParentRoute: () => rootRoute,
} as any)

const ProductIdRoute = ProductIdImport.update({
  path: '/product/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartImport
      parentRoute: typeof rootRoute
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerImport
      parentRoute: typeof rootRoute
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistImport
      parentRoute: typeof rootRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdImport
      parentRoute: typeof rootRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/shop/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryImport
      parentRoute: typeof rootRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AboutRoute,
  CartRoute,
  CustomerRoute,
  WishlistRoute,
  ProductIdRoute,
  ShopCategoryRoute,
  ShopIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/cart",
        "/customer",
        "/wishlist",
        "/product/$id",
        "/shop/$category",
        "/shop/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/cart": {
      "filePath": "cart.tsx"
    },
    "/customer": {
      "filePath": "customer.tsx"
    },
    "/wishlist": {
      "filePath": "wishlist.tsx"
    },
    "/product/$id": {
      "filePath": "product.$id.tsx"
    },
    "/shop/$category": {
      "filePath": "shop.$category.tsx"
    },
    "/shop/": {
      "filePath": "shop.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
